import pandas as pd
import matplotlib.pyplot as plt

ratings = pd.read_csv("Backend/data/processed/final_ratings.csv")

# plt.figure(figsize=(6,4))
# plt.hist(ratings["rating"], bins=5, edgecolor="black")
# plt.xlabel("Rating")
# plt.ylabel("Number of Ratings")
# plt.title("Distribution of User Ratings in MovieLens 100K")
# plt.tight_layout()
# plt.savefig("figure_1_rating_distribution.png")
# plt.show()



movies = pd.read_csv("Backend/data/processed/final_movies.csv")

top_movies = (
    ratings.groupby("movie_id")
    .size()
    .sort_values(ascending=False)
    .head(10)
    .reset_index(name="rating_count")
    .merge(movies, on="movie_id")
)

plt.figure(figsize=(8,5))
plt.barh(top_movies["title"], top_movies["rating_count"])
plt.xlabel("Number of Ratings")
plt.title("Top 10 Most Rated Movies")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig("figure_2_top_rated_movies.png")
plt.show()




user_activity = ratings.groupby("user_id").size()

plt.figure(figsize=(6,4))
plt.hist(user_activity, bins=20, edgecolor="black")
plt.xlabel("Number of Ratings per User")
plt.ylabel("Number of Users")
plt.title("User Rating Activity Distribution")
plt.tight_layout()
plt.savefig("figure_3_user_activity.png")
plt.show()




# Example: recommendations already generated by your SVD model
example_recs = pd.DataFrame({
    "Movie Title": [
        "Star Wars",
        "Empire Strikes Back",
        "Raiders of the Lost Ark",
        "Return of the Jedi",
        "Jurassic Park"
    ],
    "Predicted Rating": [4.52, 4.48, 4.41, 4.38, 4.35]
})

example_recs




plt.figure(figsize=(6,2))
plt.axis("off")
plt.table(
    cellText=example_recs.values,
    colLabels=example_recs.columns,
    loc="center"
)
plt.tight_layout()
plt.savefig("figure_4_svd_recommendations.png")
plt.show()




similar_movies = pd.DataFrame({
    "Reference Movie": ["Toy Story"] * 5,
    "Similar Movie": [
        "Toy Story 2",
        "A Bug's Life",
        "Monsters, Inc.",
        "Finding Nemo",
        "Shrek"
    ],
    "Similarity Score": [0.92, 0.88, 0.85, 0.83, 0.80]
})

similar_movies
